title: Vatsal Mandalia # your name (or website title) here
logo: "/images/VatsalMandalia_LinkedIn.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with growing experience in data analytics and programming in Python, R and SQL and a Master's degree in Physics with Astrophysics from the University of Sheffield.
  <br><br>
  <a href="https://www.linkedin.com/in/vatsal-mandalia/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
