title: Vatsal Mandalia # your name (or website title) here
logo: "/images/VatsalMandalia_LinkedIn.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist and Analyst, proficient with Python, SQL, Excel, Tableau tools, with hands-on ability in data cleaning, data analysis and data visualization.
  <br><br>
  <a href="https://www.linkedin.com/in/vatsal-mandalia/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/vatsal.mandalia/">View My Tableau Public Profile</a>

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
